# -*- coding: utf-8 -*-
"""data structure 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1orqT3ncGQGX4i2HiVrBb2eziIrbAOSAq
"""

score= [10,20,30,40,50]
sum=0
for s in score:
  sum+=s
print("총점: ",sum)

nums= [0,1,2,3,4,5,6,7,8,9]
print(nums[2:3])
print(nums[:4])
print(nums[6:])
print(nums[1:7:2])
print(nums[-7:5])
print(nums[-0])
# list는 얼마든지 연필로 쓴 것이기 때문에 바꿀 수 있다.

#list slice 안에 list를 집어넣기

nums= [0,1,2,3,4,5,6,7,8,9]
nums[2:5]=[20,30,40]
nums[6:8]=[90,91,92,93,94]
print(nums)

nums= [0,1,2,3,4,5,6,7,8,9]
nums[2:5]=[]
print(nums)
del nums[4]
print(nums)

list1=[1,2,3,4,5]
list2=[10,11]
list1=list1+list2
listadd=list1+list2
print(list1)
print(listadd)
listmulti=list2*3
print(listmulti)

for i in range(0,len(list2)):
    list2[i]=list2[i]*3
print(list2)

lol=[ [1,2,3],[4,5],[6,7,8,9]]
print(lol[0])
print(lol[2][1])
for sub in lol:
  for item in sub:
    print(item, end=' ')
  print()

nums=[1,2,3,4]
nums.append(5)
nums.insert(2,99)
print(nums)
nums.pop(2)
print(nums)

nums=[1,2,3,4]
nums[2:2]=[90,91,92]
print(nums)
nums=[1,2,3,4]
nums[2]=[90,91,92]
print(nums)

list1=[1,2,3,4,5]
list2=[10,11]
list1.extend(list2)
print(list1)
list3=list1+list2
print(list3)
print(list1)

print(list1)
list1=list1+list2
print(list1)

score=[88,95,70,100,99,80,78,50]
score.remove(100)
print(score)
del(score[2])
print(score)
score[1:4]=[]
print(score)
score.clear()
print(score)
score=[88,95,70,100,99,80,78,50]
print(score)
score[:]=[]# score.clear()와 같다.
print(score)
score=[88,95,70,100,99,80,78,50]
print(score)
del score[:]# score.clear()와 같다.
print(score)

score=[88,95,70,100,99,22,33,44,55,66]
print(score.pop())
x=score.pop()
print(x)
print(score.pop())
print(score.pop(1))
print(score.pop(-1))
print(score.pop(-1))
score.append(77)
print(score)

score=[88,95,70,100,99,80,78,50]
perfect=score.index(100)
print("만점 받은 학생은"+str(perfect)+"번 입니다.")
pernum=score.count(100)
print("만점 받은 학생은"+str(pernum)+"명 입니다.")

print("학생 수는 %d명 입니다"%len(score))
print("최고 점수는 %d점 입니다"% max(score))
print("최저 점수는 %d점 입니다"% min(score))

ans= input("결제하시겠습니까?")
if ans in ['yes','y','ok','예','당근']:
  print("구입해 주셔서 감사합니다")
else:
  print("안녕히 가세요")

score=[88,95,70,100,99]
score2=sorted(score)
print(score)
print(score2)

country =["Korea","Japan","CHINA","America"]
country.sort()
print(country)
country.sort(key=str.lower)
print(country)

score=(88,95,70,100,99)
sum=0
for s in score:
  sum+=s
print("총점 :",sum)
print("평균 :",sum/len(score))

tu=2,
value=2
value1=(2)
value2=(2,)
value3=2,3
print(tu)
print(value)

tu= "이순신", "김유신", "강감찬"
lee, kim, kang= tu
print(lee)
print(kang)
print(kim)

a,b =12,34
print(a,b)
a,b=b,a
print(a,b)

tu= tuple(score)
print(tu)
li= list(tu)
li[0]=100
print(li)

d, m= divmod(7,3)
print("몫",d)
print("나머지",m)

dic={'boy':'소년','school':'학교','book':'책'}
print(dic['boy'])
print(dic['book'])
w= input("문자를 입력하시오.")
if w not in dic:
  print("이것은 사전에 없는 단어입니다.")

dic= {'boy':'소년','school':'학교','book':'책'}
dic['boy']='남자애'
dic['girl']='소녀'
del dic['book']
print(dic)

print(dic.keys)
print(dic.values)
print(dic.items)
dic2={'student':'학생',"teacher":"선생님","book":"서적"}
dic.update(dic2)
print(dic2)

li=[['boy','소년'],['school','학교'],['book','책']]
dic=dict(li)
print(dic)
li1=list(dic)
print(li1)

song= """By the rivers of Babylon 
there he sat down,yeah he wept,when he remembered Zion,when the wicked carried us away in captivity
required from us a song now How can we sing lord's song in a strange land"""

alphabet= dict()
alphabet={}
for c in song:
  if c.isalpha()==False:
    continue
  c=c.lower()
  if c not in alphabet:
    alphabet[c]=1
  else:
    alphabet[c]+=1
print(alphabet)

key=list(alphabet.keys())
key.sort()
for c in key:
  num=alphabet[c]
  print(c,"=>",num)

asia={'korea','china','japan','Mongolia'}
asia.add('vietnam')
asia.add('china')
asia.remove('japan')
print(asia)

print(set("sanghyung"))
print(set([12,34,56,78]))
print(set(["신지희","한주완","김태륜"]))
print(set({'boy':'소년','school':'학교','book':'책'}))
print(set())

twox={2,4,6,8,10,12}
threex={3,6,9,12,15}
print("교집합",twox& threex)
print("합집합",twox|threex)
print("차집합",twox-threex)
print("차집합",threex-twox)
print("배타적 차집합",twox^threex)

mammal={'코끼리','고릴라','사자','고래','사람','원숭이','개'}
primate={'고릴라','사람','원숭이'}
if '사자' in mammal:
  print("사자는 포유류이다.")
else:
  print("사자는 포유류가 아니다.")

print(primate<=mammal)
print(primate<mammal)
print(primate<=primate)
print(primate<primate)

mammal={'코끼리','고릴라','사자','고래','사람','원숭이','개'}
primate={'고릴라','사람','원숭이'}
if '사자' in mammal:
  print("사자는 포유류이다.")
else:
  print("사자는 포유류가 아니다.")

print(primate<=mammal)
print(primate<mammal)
print(mammal<primate)
print(primate<=primate)
print(primate<primate)

a=[(x,y,z)for x in range(1,30) for y in range(x,30) for z in range(y,30)if x**2+ y**2==z**2]
print(a)

new=[]
for x in range(1,30):
  for y in range(x,30):
    for z in range(y,30):
      if x**2+y**2== z**2:
        new.append((x,y,z))
print(new)

menu=0
friend=[]
while menu!=9:
  print("---------------")
  print("1. 친구 리스트 출력")
  print("2. 친구 추가")
  print("3. 친구 삭제")
  print("4. 이름 변경")
  print("5. 종료")

  menu=int(input("메뉴를 선택하시오 :"))
  if menu==1:
    print(friend)
  elif menu==2:
    name=input("이름을 입력하시오.:")
    friend.append(name)
  elif menu==3:
    del_name=input("지우고 싶은 이름을 입력하시오.:")
    if del_name in friend:
      friend.remove(del_name)
    else:
      print("이름이 발견되지 않았음")
  elif menu==4:
    old_name=input("변경하고 싶은 이름을 입력하시오.:")
    if old_name in friend:
      index= friend.index(old_name)
      new_name=input("새로운 이름을 입력하시오.:")
      friends[index]=new_name
    else:
      print("이름이 발견되지 않았음")
  elif menu==5:
    print("종료")
    break

english_dict=dict()

english_dict['one']='하나'
english_dict['two']='둘'
english_dict['three']='셋'

word=input("단어를 입력하시오.")
  
print(english_dict.get(word,"없음"))

partyA=set(["Park","Kim","Choi"])
partyB=set(["Park","Choi"])
print("2개의 파티에 모두 참석한 사람은 다음과 같습니다.")